### ISSUE TITLE
CA100-Admins-BaseProtection-AllApps-AnyPlatform-CompliantorAADHJ  is CompliantorMFA

### ISSUE THREAD

**Issue by hugobatista** [microsoft/ConditionalAccessforZeroTrustResources#6]
Hi @clajes !
It seems that CA100-Admins-BaseProtection-AllApps-AnyPlatform-CompliantorAADHJ  is CompliantorMFA and not CompliantorAADHJ. Also, the pdf has a CA101 for Admins MFA which is not in sample policies, but at the same time it  also enforces MFA on MFAforHighSigninRisk, which seems duplicate. 

Can you help to clarify if this was a type or if you changed your point of view somehow around admins for some reason? Internals seem to have a more coherent approach, with CompliantorAADHJ and MFAforHighSignInRisk. 
Thanks

**Comment by clajes** [comment]
thanks for your input. I have changed the documentation and excel file, and now there are PDFs and Excel from October 2023. The json policies haven't been changed yet.

**Comment by hugobatista** [comment]
Thanks for taking the time to answer, @clajes  and to clarify it. The new policies make much more sense. Thanks for the help.

**Comment by clajes** [comment]
you are welcome, - thanks for reaching out to get this corrected.

**Comment by hugobatista** [comment]
Hi @clajes , 

meanwhile i submitted a PR with the sample policies with the detected changes in the Oct 2023 pdf document. 
https://github.com/microsoft/ConditionalAccessforZeroTrustResources/pull/7
